// SECOND REWARD - contains 2 chores
Retrieved KIDCHORES by kid name
Chores are: Array [
  Object {
    "category_id": 2,
    "category_name": "Kitchen",
    "chore_id": 13,
    "icon_name": "silverware-clean",
    "is_completed": 1,
    "kid_id": 2,
    "kid_name": "A",
    "reward_icon_name": "trophy",
    "reward_id": 2,
    "reward_name": "Go KArting (40)",
    "reward_points": 40,
    "task_id": 7,
    "task_name": "Whatever (10)",
    "task_points": 10,
  },
  Object {
    "category_id": 2,
    "category_name": "Kitchen",
    "chore_id": 14,
    "icon_name": "school",
    "is_completed": 0,
    "kid_id": 2,
    "kid_name": "A",
    "reward_icon_name": "trophy",
    "reward_id": 2,
    "reward_name": "Go KArting (40)",
    "reward_points": 40,
    "task_id": 8,
    "task_name": "Load Dishwasher (11)",
    "task_points": 11,
  },
]
ChoresForKid Array [
  Object {
    "chores": Array [
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 1,
        "icon_name": "silverware-clean",
        "is_completed": 1,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 1,
        "task_name": "Wash Dishes (10)",
        "task_points": 10,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 2,
        "icon_name": "silverware-fork-knife",
        "is_completed": 0,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 2,
        "task_name": "Dry Dishes (11)",
        "task_points": 11,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 3,
        "icon_name": "dishwasher",
        "is_completed": 1,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 3,
        "task_name": "Load Dishwasher (11)",
        "task_points": 11,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 4,
        "icon_name": "dishwasher",
        "is_completed": 0,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 4,
        "task_name": "Empty Dishwasher (11)",
        "task_points": 11,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 5,
        "icon_name": "dishwasher",
        "is_completed": 0,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 5,
        "task_name": "Set Table (11)",
        "task_points": 11,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 6,
        "icon_name": "dishwasher",
        "is_completed": 0,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 6,
        "task_name": "Clear Table (11)",
        "task_points": 11,
      },
    ],
    "rewardID": 1,
    "rewardIcon": "trophy",
    "rewardName": "Play Console (20)",
  },
  Object {
    "chores": Array [
      Object {
        "category_id": 2,
        "category_name": "Kitchen",
        "chore_id": 13,
        "icon_name": "silverware-clean",
        "is_completed": 1,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 2,
        "reward_name": "Go KArting (40)",
        "reward_points": 40,
        "task_id": 7,
        "task_name": "Whatever (10)",
        "task_points": 10,
      },
      Object {
        "category_id": 2,
        "category_name": "Kitchen",
        "chore_id": 14,
        "icon_name": "school",
        "is_completed": 1,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 2,
        "reward_name": "Go KArting (40)",
        "reward_points": 40,
        "task_id": 8,
        "task_name": "Load Dishwasher (11)",
        "task_points": 11,
      },
    ],
    "rewardID": 2,
    "rewardIcon": "trophy",
    "rewardName": "Go KArting (40)",
  },
]
2
A
6
2
A
6
2
A
6
2
A
6
2
A
6
2
A
6
HERE WE ARE Array []
Chores are: Array [
  Object {
    "category_id": 2,
    "category_name": "Kitchen",
    "chore_id": 13,
    "icon_name": "silverware-clean",
    "is_completed": 1,
    "kid_id": 2,
    "kid_name": "A",
    "reward_icon_name": "trophy",
    "reward_id": 2,
    "reward_name": "Go KArting (40)",
    "reward_points": 40,
    "task_id": 7,
    "task_name": "Whatever (10)",
    "task_points": 10,
  },
  Object {
    "category_id": 2,
    "category_name": "Kitchen",
    "chore_id": 14,
    "icon_name": "school",
    "is_completed": 0,
    "kid_id": 2,
    "kid_name": "A",
    "reward_icon_name": "trophy",
    "reward_id": 2,
    "reward_name": "Go KArting (40)",
    "reward_points": 40,
    "task_id": 8,
    "task_name": "Load Dishwasher (11)",
    "task_points": 11,
  },
]
ChoresForKid Array [
  Object {
    "chores": Array [
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 1,
        "icon_name": "silverware-clean",
        "is_completed": 1,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 1,
        "task_name": "Wash Dishes (10)",
        "task_points": 10,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 2,
        "icon_name": "silverware-fork-knife",
        "is_completed": 0,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 2,
        "task_name": "Dry Dishes (11)",
        "task_points": 11,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 3,
        "icon_name": "dishwasher",
        "is_completed": 1,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 3,
        "task_name": "Load Dishwasher (11)",
        "task_points": 11,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 4,
        "icon_name": "dishwasher",
        "is_completed": 0,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 4,
        "task_name": "Empty Dishwasher (11)",
        "task_points": 11,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 5,
        "icon_name": "dishwasher",
        "is_completed": 0,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 5,
        "task_name": "Set Table (11)",
        "task_points": 11,
      },
      Object {
        "category_id": 1,
        "category_name": "Kitchen",
        "chore_id": 6,
        "icon_name": "dishwasher",
        "is_completed": 0,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 1,
        "reward_name": "Play Console (20)",
        "reward_points": 20,
        "task_id": 6,
        "task_name": "Clear Table (11)",
        "task_points": 11,
      },
    ],
    "rewardID": 1,
    "rewardIcon": "trophy",
    "rewardName": "Play Console (20)",
  },
  Object {
    "chores": Array [
      Object {
        "category_id": 2,
        "category_name": "Kitchen",
        "chore_id": 13,
        "icon_name": "silverware-clean",
        "is_completed": 1,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 2,
        "reward_name": "Go KArting (40)",
        "reward_points": 40,
        "task_id": 7,
        "task_name": "Whatever (10)",
        "task_points": 10,
      },
      Object {
        "category_id": 2,
        "category_name": "Kitchen",
        "chore_id": 14,
        "icon_name": "school",
        "is_completed": 1,
        "kid_id": 2,
        "kid_name": "A",
        "reward_icon_name": "trophy",
        "reward_id": 2,
        "reward_name": "Go KArting (40)",
        "reward_points": 40,
        "task_id": 8,
        "task_name": "Load Dishwasher (11)",
        "task_points": 11,
      },
    ],
    "rewardID": 2,
    "rewardIcon": "trophy",
    "rewardName": "Go KArting (40)",
  },
]
