export default {
  Login: "Login",
  ParentDashBoard: "ParentDashBoard",
  CreateTaskListForChild: "CreateTaskListForChild",
  AddCategory: "AddCategory",
  ManageRewards: "ManageRewards",
  TrackPocketMoney: "TrackPocketMoney",
  ViewAccomplishments: "ViewAccomplishments",
  ParentChildDashBoard: "ParentChildDashBoard",
  AddReward: "AddReward",
  EditReward: "EditReward",
  AddChild: "AddChild",
  EditChild: "EditChild",
  RemoveChild: "RemoveChild",
  ViewReward: "ViewReward",
  ChildDashBoard: "ChildDashBoard",
  ChoreStatus: "ChoreStatus",
  ChoreProgress: "ChoreProgress",
  EditProfile: "EditProfile",
  TrackReward: "TrackReward",
  ViewDatabaseUsers: "ViewDatabaseUsers",
};
